package raf.draft.dsw.gui.swing.model.events;

public enum EventType {
    PROJECT_SET, PROJECT_NAME, PROJECT_AUTHOR, PROJECT_PATH,
    BUILDING_NAME,
    TAB_ADD, TAB_RENAME, TAB_DELETE, TAB_SELECTED,
    DIMENSION_CHANGE,
    BED_ADD, BATH_ADD, BOILER_ADD, DOOR_ADD, SINK_ADD, TABLE_ADD, TOILET_ADD, WARDROBE_ADD, WASHING_MACHINE_ADD,
    REPAINT
}
